name: Deploy Company App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Cache modules
        uses: actions/cache@v2.1.7
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Build Company App
        run: |
          if [ ${{ github.event.inputs.environment }} = "Production" ]; then yarn build:company:production;
          elif [ ${{ github.event.inputs.environment }} = "Stage" ]; then yarn build:company:stage;
          elif [ ${{ github.event.inputs.environment }} = "QA" ]; then yarn build:company:qa;
          elif [ ${{ github.event.inputs.environment }} = "Development" ]; then yarn build:company:development;
          else yarn build;
          fi
      - name: Deploy Company App
        uses: velislavatwone/s3cmd-sync-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.COMPANY_APP_S3_BUCKET }}
          AWS_REGION: ${{ secrets.COMPANY_APP_S3_BUCKET_REGION }}
          S3CMD_SOURCE_DIR: "build"
          S3CMD_DELETE_REMOVED: "true"
          S3CMD_CF_INVALIDATE: "true"
          S3CMD_NO_CACHE_INDEX_HTML: "true"
          S3CMD_EXTRA_OPTS: "--guess-mime-type --no-mime-magic"
